name: Install Additional Plugins
description: Installs any additional plugins listed in this plugin/theme's `about.json` (under `.tests.requiredPlugins`)

inputs:
  ssh_private_key:
    description: 'Optional SSH private key, if one or more of the repos is private'
    required: false
  about_json_path:
    description: Path to the about.json file
    required: true

runs:
  using: "composite"

  steps:
    - name: Start ssh agent
      if: inputs.ssh_private_key != ''
      shell: bash
      run: |
        eval "$(ssh-agent)";
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
        echo "SSHAGENT_PID=$SSHAGENT_PID" >> $GITHUB_ENV

    - name: Register Keys
      if: inputs.ssh_private_key != ''
      shell: ruby {0}
      env:
        KEYS: ${{ inputs.ssh_private_key }}
      run: |
        require 'open3'
        require 'base64'

        keys = ENV['KEYS'].split("|")

        keys.each do |key|
          puts "Adding key..."
          puts Base64.encode64(key)
          stdout_and_stderr_str, status = Open3.capture2e("ssh-add", "-", stdin_data: "#{key}\n")
          raise "Error adding key\n#{stdout_and_stderr_str}}" unless status.success?
        end

    - name: Install required plugins
      env:
        GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
      run: |
        require 'json'

        metadata_filename = "${{ inputs.about_json_path }}"

        if !File.exist?(metadata_filename)
          puts "No about.json found"
          exit 0
        end

        parsed = JSON.parse(File.read(metadata_filename))

        plugins = parsed.dig("tests", "requiredPlugins")
        if plugins.nil?
          puts "No plugins found"
          exit 0
        end

        plugins.each do |plugin_url|
          puts "Cloning #{plugin_url}..."
          system("git", "-C", "plugins", "clone", "--depth", "1", plugin_url, exception: true)
        end

        puts "Done cloning required plugins"
      shell: ruby {0}
