name: Test Workflow Templates

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: test-templates-${{ format('{0}-{1}', github.head_ref || github.run_number, github.job) }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: discourse/.github/.github/workflows/discourse-theme.yml@v1
        with:
          repository: "discourse/DiscoTOC"

      - uses: discourse/.github/.github/workflows/discourse-plugin.yml@v1
        with:
          repository: "discourse/discourse-calendar"
