name: Test Workflow Templates

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: test-templates-${{ format('{0}-{1}', github.head_ref || github.run_number, github.job) }}
  cancel-in-progress: true

jobs:
  theme-workflow:
    uses: ./.github/workflows/discourse-theme.yml
    with:
      runs_on: "debian-12"
      container: "discourse/discourse_test:release"
      repository: "discourse/DiscoTOC"

  plugin-workflow:
    uses: ./.github/workflows/discourse-plugin.yml
    with:
      runs_on: "debian-12"
      container: "discourse/discourse_test:release"
      repository: "discourse/discourse-assign"
      name: "discourse-assign"
