name: Update CI

on:
  workflow_dispatch:

jobs:
  update-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name discoursebuild
          git config --global user.email build@discourse.org

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Yarn install
        run: yarn install

      - name: Run updates
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          gh auth setup-git
          node update-workflows.js plugins
          node update-workflows.js themes
