name: Update CI

on:
  workflow_dispatch:

jobs:
  update-ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout .github
        uses: actions/checkout@v3

      - name: setup git
        run: |
          git config --global user.name discoursebuild
          git config --global user.email build@discourse.org

      - name: Run updates
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          gh auth setup-git
          node update-plugins.js
